### ISSUE TITLE
1.6.4初始化日志没有报错也没有生成ledger-binding.conf文件

### ISSUE THREAD

**Issue by Rebecca2527** [jd-opensource/jdchain_bak#95]
启动时控制台日志：
![1666337833780](https://user-images.githubusercontent.com/41558768/197140029-ec9ea6ad-e92b-4046-9b77-abfa399ce90b.png)
init.log
![1666337938978](https://user-images.githubusercontent.com/41558768/197140368-5570a7fd-30f6-4408-8631-5aa50b9f8d62.png)

**Comment by imuge** [comment]
参照 https://jdchain.s3.cn-north-1.jdcloud-oss.com/videos/install.mp4 操作试试
