### ISSUE TITLE
生成配置文件报错

### ISSUE THREAD

**Issue by Q3B0** [jd-opensource/jdchain_bak#99]
Unmatched argument at index 0: 'jdchain-cli-1.6.5.RELEASE.jar:Zone.Identifier'

**Comment by imuge** [comment]
什么系统及java版本？ @Q3B0

**Comment by Q3B0** [comment]
> 什么系统及java版本？ @Q3B0

ubuntu 20.04 jdk17

**Comment by imuge** [comment]
jdk 17 没有测试过，推荐使用8先试下
